In [1]:
from ddgs import DDGS
from fastai.vision.all import *
from fastai.vision.widgets import *

In [2]:
def search_images(keyword, max_images=200):
    return L(DDGS().images(keyword, max_results=max_images)).itemgot('image')

In [3]:
bear_types = 'grizzly', 'teddy', 'black'
path = Path('bears')

In [4]:
# if not path.exists():
#     path.mkdir()

# for bear in bear_types:
#     dest = (path/bear)
#     dest.mkdir(exist_ok = True)
#     images = search_images(f'{bear} bear')
#     download_images(dest, urls=images)

In [5]:
fns = get_image_files(path)
fns

[Path('bears/black/0042a473-d394-463c-b4d8-62daf9b246a6.jpg'), Path('bears/black/0168f4dc-f186-4867-8835-e05d460bfdd6.jpg'), Path('bears/black/0be1d257-0753-44c7-809c-aefb2d62bdd8.jpg'), Path('bears/black/0cd9686b-7bdb-4d93-aef4-5d67af389762.jpg'), Path('bears/black/111af38e-6d1d-4bf0-a232-4af41ba6c18a.jpg'), Path('bears/black/12acc60a-ca21-4f5b-b49e-47315551df87.jpg'), Path('bears/black/179adaa3-7d9a-40f7-8f7e-e5489383a5ae.jpg'), Path('bears/black/183da35d-6355-4fab-82a6-48e86a4e720d.jpg'), Path('bears/black/195dfe3b-03ad-4490-b327-c64911bd5318.jpg'), Path('bears/black/1ab0f27a-0d03-483c-9d27-ee4fed029fc3.jpg'), Path('bears/black/1acbab46-921b-47cb-83c9-17197ce33af4.jpg'), Path('bears/black/1b311dc2-d354-497b-b0d4-824f888bbeb1.jpg'), Path('bears/black/1fb313aa-b926-4e9d-9552-1e82fdba8358.jpg'), Path('bears/black/238ad1f2-adc8-4e27-837c-e665aa7c5cb3.jpg'), Path('bears/black/2782c64d-66a6-446e-adc4-952d080ace0f.jpg'), Path('bears/black/31169d93-f9d4-4935-bfe9-30cf7cf188d9.jpg'), Path('bears/black/316ba706-c03a-47b9-8dac-2374b5aafb94.jpg'), Path('bears/black/340adf10-bd1c-4737-9208-ca38e2dc72f8.jpg'), Path('bears/black/37bae5e7-53b1-4b8e-8e46-790439259abf.jpg'), Path('bears/black/38b5f1a6-edbd-45b3-9c46-bd510fb6b888.jpg'), Path('bears/black/391a2291-ca61-45f8-a3f7-ac0577b1cbe9.jpg'), Path('bears/black/3a3634c2-1b10-4520-a51e-ba93eec244c7.jpg'), Path('bears/black/3aef0d5f-88ed-47e7-806c-279f625ceb91.jpg'), Path('bears/black/41194d7d-e65a-4735-b839-abd22154639d.jpg'), Path('bears/black/43ae24f1-11a5-4871-8797-b281b4dd9230.jpg'), Path('bears/black/44f641e2-d323-4449-a14a-8be829599828.jpg'), Path('bears/black/45780ab4-2d7b-456b-8e7d-d4f36c6f05e6.jpg'), Path('bears/black/46368515-e30e-4163-8533-d4160a9cae71.jpg'), Path('bears/black/50e47d21-d69c-4dfb-ae94-28563b0fb5bf.jpg'), Path('bears/black/529cb0bd-9b11-4597-9d80-8d0e7251268c.jpg'), Path('bears/black/53990e86-fa55-44ea-8542-c232a7e8c272.jpg'), Path('bears/black/5634a8b4-0f51-4065-a16e-224be8699e64.jpg'), Path('bears/black/5b512888-0954-402e-94d8-e30d129bec4b.jpg'), Path('bears/black/6271f0cd-3c97-47f2-9201-56d5caa86f00.jpg'), Path('bears/black/64bf1665-a344-46eb-b25a-fc67480e05e4.jpg'), Path('bears/black/657ec360-1368-48ed-a7f1-21242d5bce7a.jpg'), Path('bears/black/6d1040fc-fa89-4ce5-b378-7ab268eb9a4e.jpg'), Path('bears/black/6d6c68e1-a8f8-4639-baa8-c6522b8476f5.jpg'), Path('bears/black/700e9dc5-1435-45d4-ad4b-fd4a5170ca4e.jpeg'), Path('bears/black/7138d064-1f94-42f3-93d1-dfd451932233.jpg'), Path('bears/black/77f6f3a4-3b47-47c1-a7cb-76d973262f5c.jpg'), Path('bears/black/79f6af4d-07fb-46a1-ae73-c90ef7dc45b0.jpg'), Path('bears/black/7b580b00-59bd-4203-980b-c264e127e1c6.jpg'), Path('bears/black/7e1d1eb3-874f-4c9b-833c-4113ee47e0f0.jpg'), Path('bears/black/8151906b-4375-4c4b-8322-db79da076a31.jpg'), Path('bears/black/8754bf27-1870-40a9-9b1d-e0cf84e6f50b.jpg'), Path('bears/black/884be561-0e7d-497e-a652-5c346353db6f.jpg'), Path('bears/black/889d71db-69c5-4b5c-92bc-44640472ae20.jpg'), Path('bears/black/894014df-eb8e-4ee8-85cf-589378419411.jpg'), Path('bears/black/8b22519c-f2bf-4c60-a310-008e64318c1d.jpg'), Path('bears/black/93b57a35-df13-405d-a0fb-495a073a33ae.jpg'), Path('bears/black/9722d663-549e-4f06-acd6-bdb737d29805.jpg'), Path('bears/black/9b8b27e7-66ee-485b-b075-85b21fd30779.jpg'), Path('bears/black/9e116663-8bea-4e10-b11c-80189aeedc88.jpg'), Path('bears/black/a278526d-c238-4bca-a584-abdbb07eb570.jpg'), Path('bears/black/a37b1ab6-f66b-4e72-b1c1-270beaf06ab9.jpg'), Path('bears/black/a5dc5358-0f1d-4ac6-a81a-7dd079a38491.jpeg'), Path('bears/black/aaebc21f-4210-4171-a044-583ac9f6c3a9.jpg'), Path('bears/black/acc26642-0fa8-4635-a2af-0b46ff262ab6.jpg'), Path('bears/black/adda09e4-fc4b-4d6b-833e-2bfb68858917.jpg'), Path('bears/black/b488f412-3027-4919-9bd0-5ae05ac48dfc.jpg'), Path('bears/black/b6b2b4b7-1d36-426f-86e2-383288380659.jpg'), Path('bears/black/b6bddea2-2429-4d09-932d-2edb4e5990f3.jpg'), Path('bears/black/b6d93823-1e3a-4964-8d2f-492598b0aabe.jpg'), Path('bears/black/b8f6e2f9-0020-4745-9b4e-908087acd274.jpg'), Path('bears/black/be9661f8-d891-488b-8500-09916c45d36c.jpg'), Path('bears/black/c557da85-e96a-4190-902f-4c4f12e1b68f.jpg'), Path('bears/black/d1802433-7902-4f1a-b4d0-8d35aea33226.jpg'), Path('bears/black/d2413950-2ba7-433b-983c-0292965d2a95.jpg'), Path('bears/black/dad9db0e-22e4-4df8-a041-6c0641025dd1.jpg'), Path('bears/black/dfbddf88-0668-4f06-9a01-4fd192d30fa6.jpg'), Path('bears/black/e02c2b3b-6697-4189-9608-b0d927a4309f.jpg'), Path('bears/black/e0cc0b0e-eb1a-457a-8464-ea568e0ccf75.jpg'), Path('bears/black/e2bf7ee6-aa2b-4071-90c9-fd47f3d24b15.jpg'), Path('bears/black/e5e46c00-addb-444c-8dc6-a3724fae1912.jpg'), Path('bears/black/e62fed6e-2cda-40f3-b49f-3ca760709f0e.jpg'), Path('bears/black/e77a183b-4bb6-41e3-834d-0bf2cbe0f304.jpg'), Path('bears/black/e7d5e5d3-9e35-4564-9b62-7a7d3d9e13ec.jpg'), Path('bears/black/f361500f-1ae8-42fc-ac8a-b4daa33d4d33.jpg'), Path('bears/black/f4570180-6213-4a56-89ca-f187659642d0.jpg'), Path('bears/black/f7432192-e4f8-4cf3-be22-eff31c280bba.jpg'), Path('bears/black/f789a823-3fbe-4e63-b1e0-d4f67e167f58.jpg'), Path('bears/black/fa62dae0-44f8-4d08-bf5d-1946c6c21908.jpg'), Path('bears/grizzly/03179023-330b-4276-a4b0-bac5a7b78b9e.jpg'), Path('bears/grizzly/06d74b78-b284-4778-95c6-25573b48fa09.jpg'), Path('bears/grizzly/090b2390-07dc-41d2-8ab6-a3b02bac1001.jpg'), Path('bears/grizzly/09163af5-28d2-4924-babe-2961b98d2489.jpg'), Path('bears/grizzly/09d88708-91b4-4e3e-b072-660573769ab4.jpg'), Path('bears/grizzly/129bd56b-c9d4-49de-94b4-154fc3569e64.jpg'), Path('bears/grizzly/1f3fbba6-85dc-4a9b-b621-bf8bd5b4360f.jpg'), Path('bears/grizzly/245b4b5a-968e-4415-95a1-79cf4c30affe.jpg'), Path('bears/grizzly/2613cf97-11e6-4738-bdad-17408278da72.jpg'), Path('bears/grizzly/273882b6-4848-46b9-8e48-0aeeb06639a0.jpg'), Path('bears/grizzly/290c57a5-7110-4cb0-a3be-c976eab9f6be.jpg'), Path('bears/grizzly/2a63e2aa-46aa-483e-bd36-f67805e017e3.jpg'), Path('bears/grizzly/2c64f9ed-c190-45a4-b66d-9050493e2f7d.jpg'), Path('bears/grizzly/2e76ccf9-581b-48ed-ad6a-98de9b239143.jpg'), Path('bears/grizzly/30b9f579-731f-451a-8513-9a416940f27d.jpg'), Path('bears/grizzly/32693ae9-b45d-4893-8bda-abe7fbf35ece.jpg'), Path('bears/grizzly/389dc437-7599-4ba3-a083-c3781f13e72b.jpg'), Path('bears/grizzly/3ba8dc12-5e28-496f-ba37-99d5f7367a57.jpg'), Path('bears/grizzly/3cdbf7d5-9ef3-4589-97c7-ead06eba18b6.jpg'), Path('bears/grizzly/3e7a5c61-7ebf-4b9e-9d82-c85a3b537436.jpg'), Path('bears/grizzly/43bc1ce1-8022-4a1e-9d52-f667dff42ce8.jpg'), Path('bears/grizzly/470e3aba-9378-4fdd-a4f2-7907210d7659.jpg'), Path('bears/grizzly/491027ef-c855-49e0-9f86-0f4892ef8607.jpg'), Path('bears/grizzly/496e25d4-45c3-4dca-9c49-af2ec825fe38.jpg'), Path('bears/grizzly/50905fbf-522d-4871-aa28-b69ddd490b84.jpg'), Path('bears/grizzly/5153aff2-602f-4785-963d-a1e0bbe2f88d.jpg'), Path('bears/grizzly/51791ae4-1532-4a5a-a023-f21d7b4ad4f8.jpg'), Path('bears/grizzly/541e5f27-9ec3-471c-8f81-d17e1285103b.jpg'), Path('bears/grizzly/56135267-303b-463c-b2ba-0705ace84897.jpg'), Path('bears/grizzly/579896b3-829a-4e14-8ac4-2a107f736de8.jpg'), Path('bears/grizzly/59bccd65-f70e-487c-acb4-fafd442749bf.jpg'), Path('bears/grizzly/6002117e-1087-4ae4-8899-d0bd2e926ba8.jpg'), Path('bears/grizzly/61f48508-08b9-44e8-a7a3-a322a371e166.jpg'), Path('bears/grizzly/6d0f3e7f-e89c-4a6d-9a56-82882ec338ed.jpg'), Path('bears/grizzly/6fac8204-31e5-489e-8604-f13e02199c60.jpg'), Path('bears/grizzly/796e1a45-ecc0-46ba-ac11-4e06f6243f0b.jpg'), Path('bears/grizzly/7ea89df3-ee94-4be7-b5e8-23c9275c73e8.jpg'), Path('bears/grizzly/8085d28b-ea14-478c-b3f5-e64205fe03c4.jpg'), Path('bears/grizzly/87715e07-221b-46b5-b5eb-3b48e6d4cf4a.jpg'), Path('bears/grizzly/87af65aa-e8bb-4d33-9ae0-870f422109d2.jpg'), Path('bears/grizzly/87bf4a1d-20c6-4902-acca-e8360b29e70a.jpg'), Path('bears/grizzly/887bed02-de4b-4f49-b1bb-25fe936ddb4e.jpg'), Path('bears/grizzly/918623a5-f169-44b0-a227-2c3dd096d5f0.jpg'), Path('bears/grizzly/965a3ae1-1d08-45e8-807e-9fc1ba73a9e8.jpg'), Path('bears/grizzly/96823a86-c556-4ee0-9d1f-96778aacd442.jpg'), Path('bears/grizzly/9ab30149-b7c5-4c2f-9a6b-e33d86647f67.jpg'), Path('bears/grizzly/a3d81248-1235-43b6-b4fa-b72f8f0b20f6.jpg'), Path('bears/grizzly/a4cd20e4-5c04-4ad6-8295-b05713cb4909.jpg'), Path('bears/grizzly/af0f76f0-9d46-4666-9d2c-a8c19743f21c.jpg'), Path('bears/grizzly/afa1a863-fbef-4d5e-b0f9-412cb07c4c5d.jpg'), Path('bears/grizzly/bd81d2ab-ccfc-4ad2-8a73-c4960ac09a3a.jpg'), Path('bears/grizzly/bec1703c-0677-410d-b164-54bd1a5a662f.jpg'), Path('bears/grizzly/c0a84f61-87bb-44ad-af66-e4afadf9cce1.jpg'), Path('bears/grizzly/c82e935f-3bc0-4b5f-9aaf-450a3490eec3.jpg'), Path('bears/grizzly/cb4fa519-b117-4397-b9e2-9195b6357606.jpg'), Path('bears/grizzly/cc75dd8e-8cb3-4500-bec0-1176a5af977a.webp'), Path('bears/grizzly/cd0accb0-095d-4d01-b38d-edb2bfdd6d14.jpg'), Path('bears/grizzly/d32a62a4-d9d6-4a53-ab74-d3be4d43e633.jpg'), Path('bears/grizzly/d6052d94-f093-4a82-a2a7-6a17929bb42c.jpg'), Path('bears/grizzly/d63309cc-7503-434b-801d-db18c50263f1.jpg'), Path('bears/grizzly/dd28e706-8de3-4d75-8c2f-ef056acf386f.jpg'), Path('bears/grizzly/e7a2c9bb-64ac-476f-ac02-1ddc57fef1f8.jpg'), Path('bears/grizzly/ebaea923-d21e-4eac-a6f4-46930f85f094.jpg'), Path('bears/grizzly/ed33d954-9837-4768-bd6c-52005f6b59cd.jpg'), Path('bears/grizzly/ed97ebeb-a758-49a6-adbe-7c7faddfb7e8.jpg'), Path('bears/grizzly/f12519b0-7f7e-4842-873e-cfe59c5b000e.jpg'), Path('bears/grizzly/f218008b-b6af-4bb5-9faa-c1d925fc6379.jpg'), Path('bears/grizzly/f27d7691-916e-4069-8190-363a951aab6c.png'), Path('bears/grizzly/f389ccd5-8a45-457b-a796-dca15bfbbc5b.jpg'), Path('bears/grizzly/f6a7e110-f796-4849-835f-40b8b256e401.jpg'), Path('bears/grizzly/fd5fbedb-e065-4be8-95ab-98d4c36f5e0e.jpg'), Path('bears/grizzly/fd9bf63b-f792-4587-adbe-6d0c9d990e1a.jpg'), Path('bears/grizzly/feffaf43-0f82-4c04-810b-f930600317c1.jpg'), Path('bears/grizzly/ffbcb0bb-6be8-4f59-b7fa-91b688cbcefd.jpg'), Path('bears/teddy/0618ef73-e477-40dc-b0f9-533361a93dbb.jpg'), Path('bears/teddy/08078440-6a27-4509-b8fa-47fa7b22668e.png'), Path('bears/teddy/0a41c0a4-a3bf-4f2c-a7b7-076799e655de.jpg'), Path('bears/teddy/0b4fbab3-fe25-4b81-a4a5-589e481fde6f.jpg'), Path('bears/teddy/0cadd18e-d214-462e-a363-aeb7bbb8d730.jpg'), Path('bears/teddy/13511a31-0f6b-45c7-949c-ee1cbb2f33c1.jpg'), Path('bears/teddy/15d48839-fcaa-4e51-b97b-f5987016b865.jpg'), Path('bears/teddy/1a2c37c6-2d03-48f7-b4ce-dca954181fa9.png'), Path('bears/teddy/1e7a0739-fe94-419c-b3ff-c7f268d074c9.jpg'), Path('bears/teddy/1fe667ff-b731-46be-928f-73b707f5b505.jpeg'), Path('bears/teddy/1fe84e57-0703-43fc-a337-8b9859d0e195.jpg'), Path('bears/teddy/2482b211-3e30-4a9c-aac6-ff7f67f6ac97.jpg'), Path('bears/teddy/24844e67-7447-477d-8182-da4b4fd86b69.jpg'), Path('bears/teddy/25570043-8d19-4123-ac8b-bcce78e045b7.jpg'), Path('bears/teddy/271199bf-ca2e-46d8-ae72-eda1b840afed.jpg'), Path('bears/teddy/28174967-ae7b-4614-88eb-cadfdf2797d4.jpg'), Path('bears/teddy/33d15057-a5f0-4746-afc9-5901985bc830.jpg'), Path('bears/teddy/3b275180-799a-4155-832c-3601c2891d94.webp'), Path('bears/teddy/3bdab38c-bba5-4a60-93a4-10482fe06c72.jpg'), Path('bears/teddy/3ca4f4f9-9411-4cdc-a780-507fce2b1433.jpg'), Path('bears/teddy/4020fbe5-b6ce-4750-bc3a-110d9326111c.jpg'), Path('bears/teddy/410b8849-50b2-47a6-af0a-199f61baeb7a.jpg'), Path('bears/teddy/41c687a0-faa7-43a1-bf99-d56df431dace.jpg'), Path('bears/teddy/432e6f8e-4bdf-4a04-8120-37bbac44dfd8.jpg'), Path('bears/teddy/441f4544-d06e-4450-bf5d-ea94f44355a4.jpg'), Path('bears/teddy/45dfcf07-8f60-4d82-8c75-e307a5f95fc0.jpg'), Path('bears/teddy/54e0c69a-522d-45f4-ae3e-4de42e3ad156.jpg'), Path('bears/teddy/554f8ab1-12fe-4ec9-94e5-0ee5abc511fe.jpg'), Path('bears/teddy/5a144f80-6f49-401a-8b08-bc884ca1e3d3.png'), Path('bears/teddy/5ff75ec0-94f6-44b1-ae4b-9265a2c697d1.png'), Path('bears/teddy/630d7b06-9cf0-4271-aeed-deb1312a95fb.jpeg'), Path('bears/teddy/64f22730-60ba-448e-a1f6-8fadf2ebd6ae.jpg'), Path('bears/teddy/663c7d0f-ab6d-41c4-ba02-b751c0d347d3.jpg'), Path('bears/teddy/682e3d3e-ebbf-4761-aee9-c9c10da0727f.png'), Path('bears/teddy/69f5028e-fa94-428b-b641-6026b7be2d2c.png'), Path('bears/teddy/6c460ed1-a9f4-4059-9cf0-fbe93589bec8.jpg'), Path('bears/teddy/6c6a35d3-1a40-4bc2-985d-d366a07dcb8f.jpg'), Path('bears/teddy/6ca4523d-8735-468d-9e1f-fdf80f48f113.jpg'), Path('bears/teddy/6cc8b4b7-a113-4fde-b240-05f8b985d2cb.jpg'), Path('bears/teddy/7831e9f5-8b9e-41f8-815b-c806f1fb0f01.png'), Path('bears/teddy/7ae59b90-0113-4758-9fbc-05c37a45d97e.jpg'), Path('bears/teddy/7ea8e917-aab1-4879-88c1-63c01cf516bf.jpg'), Path('bears/teddy/81749b03-a61c-4aee-af8d-d6f0a3299f68.jpg'), Path('bears/teddy/82c642f8-c06f-44d1-822e-6b979eb4aad7.jpg'), Path('bears/teddy/83a6de2d-350e-428d-8c4a-fc41d5e65e8d.jpg'), Path('bears/teddy/84158da8-ccbb-4501-b6f8-e35f5ffa3441.jpg'), Path('bears/teddy/8642c1e4-7aac-4ae6-85e3-292c13083f2e.jpeg'), Path('bears/teddy/87994ba6-c74e-443a-93fb-0d40f5917c39.jpg'), Path('bears/teddy/87f3e6ac-d292-4fd6-a85d-13ba52255580.jpg'), Path('bears/teddy/88a9848e-d0ad-4ab2-ac9f-b68b192ffbfa.jpg'), Path('bears/teddy/a24bc2a0-296b-4bcf-94de-6cbd6c74505b.jpeg'), Path('bears/teddy/a2a8ebae-5b41-4ef8-be89-a05b5e6a4e9e.jpg'), Path('bears/teddy/a5cbf6ea-f9af-4a8e-8c62-7cb3aa4e697c.jpg'), Path('bears/teddy/a9a6b508-6eaa-4ce3-a820-ca846120020a.jpg'), Path('bears/teddy/ab3f610a-d987-4b88-a63b-a63cb9cea7a0.jpg'), Path('bears/teddy/ae8d24a8-4adc-4093-903f-dee7f15a6e97.jpg'), Path('bears/teddy/b1f1ffd4-5ffd-498c-9799-6dd92d3b997e.jpg'), Path('bears/teddy/b6c5b81f-f9aa-4071-ac67-275b30be1cad.jpg'), Path('bears/teddy/b8661298-cac1-4afd-b970-1808023c0d11.png'), Path('bears/teddy/b9d83089-4fe3-40f7-b30c-6150b047e3b0.jpg'), Path('bears/teddy/ba0b8cc3-9ec7-4377-9b14-db5929b18d09.png'), Path('bears/teddy/bc044417-76d9-449c-8dd1-4c192f5da42b.jpg'), Path('bears/teddy/bd3e233f-3bab-461a-a083-153bf3d42c49.jpg'), Path('bears/teddy/be2b81c8-eca9-4e64-a39f-1492d4032cd5.jpg'), Path('bears/teddy/c0b4732a-c3f8-45a6-8799-58bde1d76392.jpg'), Path('bears/teddy/c1f4f056-3615-4e0e-82b2-b8879321f963.jpeg'), Path('bears/teddy/c2fa40e9-2d12-43c7-9d8e-a801feae1691.jpg'), Path('bears/teddy/c32d2bc7-6596-4070-9fce-d3ef01aa270a.jpg'), Path('bears/teddy/c397850e-d058-417d-9960-85241535f024.jpg'), Path('bears/teddy/c4b58c35-ff71-4034-ab71-480e7182cca7.png'), Path('bears/teddy/c5edfd59-c46d-42f1-b444-1496409ab739.jpg'), Path('bears/teddy/c6c38797-f7aa-4e41-b0b2-543a4dba2c1f.jpg'), Path('bears/teddy/c706eee9-2f7e-40a0-bb58-d5ea088ef71f.jpg'), Path('bears/teddy/caa2a0c4-a3b0-44ef-9207-9a9bc40ff61d.jpg'), Path('bears/teddy/ccc55122-eda9-4f55-b19f-4fed710c1a3f.jpg'), Path('bears/teddy/cd6e9e3f-a3ed-4f58-acf3-bf5b1fbc3a04.jpg'), Path('bears/teddy/ce03a49b-106f-4a9c-b32a-207656123d23.png'), Path('bears/teddy/cf66a098-7039-4873-b923-98f2e160c96e.jpg'), Path('bears/teddy/cfede8fa-84c0-40df-82fc-3b94633f7798.jpg'), Path('bears/teddy/d0f0070a-1c75-4674-a491-e3a768a3b4d7.webp'), Path('bears/teddy/d335c11c-f64e-422c-9765-ff779026e80b.jpg'), Path('bears/teddy/d5c9a816-d8ad-4faf-bdb3-425c8db77a57.jpg'), Path('bears/teddy/d66ed548-de81-4e8b-8d24-9b1961b27e04.jpg'), Path('bears/teddy/daee4d67-ace7-45a9-aef0-3b1cf67104d4.jpg'), Path('bears/teddy/e26f89d7-ed0c-4118-abf6-5db539c21364.png'), Path('bears/teddy/e3adae52-6748-48fe-bdc4-8fd5ac6e12b6.png'), Path('bears/teddy/ea70dcc7-99e4-4adb-ae82-657730a4a166.jpg'), Path('bears/teddy/ecf82909-4dab-4162-9498-9bfe0321a895.jpg'), Path('bears/teddy/f0fcb209-ec4e-42d6-a2d8-dba4e70fdeba.jpg'), Path('bears/teddy/f4c4d736-1f47-4311-a5e2-e6434d2cb2ec.jpg'), Path('bears/teddy/ff6fc38a-59c7-4a02-b0ec-00d7a70ae49e.jpg')]

In [6]:
# failed = verify_images(fns)
# print(len(failed))
# failed.map(Path.unlink)

In [7]:
# doc(verify_images)

In [8]:
bears = DataBlock(
    blocks = (ImageBlock, CategoryBlock),
    get_items = get_image_files,
    splitter = RandomSplitter(valid_pct = 0.2, seed = 42),
    get_y = parent_label,
    item_tfms = Resize(128)
)

In [9]:
dls = bears.dataloaders(path)

In [10]:
# dls.show_batch(max_n = 6, nrows = 1)

In [11]:
# bears = bears.new(item_tfms = Resize(128, ResizeMethod.Squish))
# dls = bears.dataloaders(path, bs = 32)
# dls.show_batch(max_n = 6, nrows = 1)

In [12]:
# bears = bears.new(item_tfms = Resize(128, ResizeMethod.Pad, pad_mode = 'zeros'))
# dls = bears.dataloaders(path)
# dls.show_batch(max_n = 6, nrows = 1)

In [13]:
# bears = bears.new(item_tfms = RandomResizedCrop(128, min_scale = 0.3))
# dls = bears.dataloaders(path)
# dls.show_batch(max_n = 6, nrows = 1, unique = True)

In [14]:
# bears = bears.new(item_tfms = Resize(128), batch_tfms = aug_transforms(mult=2))
# dls = bears.dataloaders(path)
# dls.show_batch(max_n = 8, nrows = 2, unique = True)

In [15]:
bears = bears.new(
    item_tfms = RandomResizedCrop(128, min_scale = 0.5),
    batch_tfms = aug_transforms()
)
dls = bears.dataloaders(path)

In [16]:
learn = vision_learner(dls, resnet18, metrics = error_rate)
learn.fine_tune(4)

c:\Anaconda\envs\jhp313\Lib\site-packages\PIL\Image.py:1034: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

In [17]:
# inter = ClassificationInterpretation.from_learner(learn)
# inter.plot_confusion_matrix()

In [18]:
# inter.plot_top_losses(5, nrows=1)

In [19]:
# cleaner = ImageClassifierCleaner(learn)
# cleaner

In [20]:
# for idx in cleaner.delete():
#     cleaner.fns[idx].unlink()

# for idx, cat in cleaner.change():
#     shutil.move(str(cleaner.fns[idx]), path/cat)

In [21]:
learn.export('bears.pkl')

In [22]:
learn.export('bears.pth')

In [23]:
!pip freeze > requirements.txt